### ISSUE TITLE
It uses Jekyll

### ISSUE THREAD

**Issue by arranf** [DarthEmpty/DarthEmpty.github.io#1]
It should be built in Hugo.

**Comment by arranf** [comment]
It still uses Jekyll.

**Comment by arranf** [comment]
It still uses Jekyll. Still.

**Comment by DarthEmpty** [comment]
Thank you for your ever-valued input on this topic. Because you brought this to our attention, this bug is now fixed! :+1: The site uses Hugo instead of Jekyll
